name: build-intar-agent-cross

on:
  pull_request:

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          targets: ${{ matrix.target }}

      - name: Install cross
        uses: taiki-e/setup-cross@v1

      - name: Build intar-agent with cross
        run: cross build --package intar-agent --release --target ${{ matrix.target }} --locked
